server:
  port: 3008
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.172.82:3306/busroutes?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: busroutes
    password: absolutelyshuaib
  application:
    name: SpringBootApplication
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 200MB
  resources:
    static-locations: classpath:static/
  jpa:
    open-in-view: false

logging:
  level:
    root: warn
    com.mp.first_mp.dao: trace
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

config:
  jwt:
    # 加密密钥
    secret: absolutelyshuaib
    # token有效时长
    expire: 604800
    # header 名称
    header: token


